# 안녕하세요^^ 
## '서울시 생활정보 기반 대중교통 수요 분석 ' 과정에 오신 여러분을 환영합니다.
* 본 과정에서는 실제 사례와 데이터를 기반으로 문제를 해결하는 전체 과정을 자기 주도형 실습으로 진행해볼 예정입니다.
* 앞선 교육과정을 정리하는 마음과 지금까지 배운 내용을 바탕으로 문제 해결을 해볼게요!
* 미니 프로젝트를 통한 문제 해결 과정 'A에서 Z까지', 지금부터 시작합니다!

# 데이터 분석부터 먼저 시작해보겠습니다.
### "구별 등록인구 데이터" 를 확인해 보도록 하겠습니다

# 필요 라이브러리부터 설치합니다.
%pip install pandas seaborn

## 기본전제
* 처음에 제공되는 데이터는 'raw_data' 폴더에 있습니다.

[기본 데이터]
* 1.3 seoul_people.csv

[데이터 소개]
* 서울 시 주민 등록 데이터

[변수 소개]
* 한국인 / 등록 외국인 / 합계 / 세대수 / 고령인구수

# 1.데이터 불러오기
### 모든 미니 프로젝트의 시작은 '데이터 불러오기' 부터라고 할 수 있습니다.
+ KeyPoint : 불러오고자 하는 데이터에 따라 자유롭게 변수로 지정할 수 있다.

###  데이터 프레임을 불러오고 변수로 저장(여기서는 CSV 기준으로 진행)
* csv : pd.read_csv("파일이름. csv")
* txt : pd.read_csv("파일이름. csv", sep="구분자")
* xlsx : pd.read_excel('파일이름.xlsx')
* pickle : pd.read_pickle("파일이름.pkl") <br>
 [참고] pickle은 파이썬의 모든 객체를 파일로 저장할 수 있는 방법으로 DataFrame,List,Dict 등 모든 객체 저장 가능(특히 sklearn라이브러리를 통해 모델을 학습시키고, 저장할 때 많이 사용)

#### [실습문제1] 데이터 로딩
* '1.3 seoul_people.csv'파일을 'seoul_people' 변수에 저장하고 그 Shape을 확인하세요.
    * 데이터 파일 로딩시 참고 사항 
        * 구분자(sep)는 '\t' 입니다
        * cp949 인코더를 사용해 주세요

In [1]:
import pandas as pd

In [2]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
seoul_people = pd.read_csv('1.3 seoul_people.csv',sep="\t", index_col = 0, encoding = 'cp949')

In [3]:
# 데이터 프레임의 Shape을 확인합니다.
seoul_people.shape

(28, 13)

# 2.기본 정보 확인 및 클렌징

+ 데이터 클렌징 : 결측치, 이상치 등을 제거하여 데이터 분석 결과가 왜곡 되는 문제를 방지하기 위한 정제 과정

#### [실습문제2] 기본 정보 확인하기
* 'seoul_people' 데이터의 정보를 확인해보세요.
* 'describe', 'info', 'head' 등 전부 활용해 보겠습니다.

In [4]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
seoul_people.head()

,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
기간,,,,,,,,,,,,,
기간,자치구,세대,합계,합계,합계,한국인,한국인,한국인,등록외국인,등록외국인,등록외국인,세대당인구,65세이상고령자
기간,자치구,세대,계,남자,여자,계,남자,여자,계,남자,여자,세대당인구,65세이상고령자
2022.1/4,합계,4451444,9732617,4716704,5015913,9506778,4613910,4892868,225839,102794,123045,2.14,1628980
2022.1/4,종로구,73766,153684,74018,79666,144275,69911,74364,9409,4107,5302,1.96,28064
2022.1/4,중구,63767,131450,63869,67581,122173,59448,62725,9277,4421,4856,1.92,24742

In [5]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
seoul_people.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28 entries, 기간 to 2022.1/4
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   자치구       28 non-null     object
 1   세대        28 non-null     object
 2   인구        28 non-null     object
 3   인구.1      28 non-null     object
 4   인구.2      28 non-null     object
 5   인구.3      28 non-null     object
 6   인구.4      28 non-null     object
 7   인구.5      28 non-null     object
 8   인구.6      28 non-null     object
 9   인구.7      28 non-null     object
 10  인구.8      28 non-null     object
 11  세대당인구     28 non-null     object
 12  65세이상고령자  28 non-null     object
dtypes: object(13)
memory usage: 3.1+ KB

#### [실습문제3] 데이터 확인 및 처리

* head 와 tail 을 보고, 어느 데이터만 가져와야 할지 생각 해 봅시다.

In [6]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# 한국인 남자 여자 계 세대당 인구 65세이상 고령자 자치구만 가져오기
seoul_people.head()

,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
기간,,,,,,,,,,,,,
기간,자치구,세대,합계,합계,합계,한국인,한국인,한국인,등록외국인,등록외국인,등록외국인,세대당인구,65세이상고령자
기간,자치구,세대,계,남자,여자,계,남자,여자,계,남자,여자,세대당인구,65세이상고령자
2022.1/4,합계,4451444,9732617,4716704,5015913,9506778,4613910,4892868,225839,102794,123045,2.14,1628980
2022.1/4,종로구,73766,153684,74018,79666,144275,69911,74364,9409,4107,5302,1.96,28064
2022.1/4,중구,63767,131450,63869,67581,122173,59448,62725,9277,4421,4856,1.92,24742

In [7]:
seoul_people.tail()

,자치구,세대,인구,인구.1,인구.2,인구.3,인구.4,인구.5,인구.6,인구.7,인구.8,세대당인구,65세이상고령자
기간,,,,,,,,,,,,,
2022.1/4,관악구,279353,500336,250450,249886,486375,244409,241966,13961,6041,7920,1.74,80686
2022.1/4,서초구,169895,413677,197665,216012,409823,195806,214017,3854,1859,1995,2.41,61404
2022.1/4,강남구,234612,537338,257096,280242,532577,254866,277711,4761,2230,2531,2.27,79575
2022.1/4,송파구,285106,668261,321963,346298,662607,319407,343200,5654,2556,3098,2.32,99854
2022.1/4,강동구,201926,465097,227891,237206,461300,226203,235097,3797,1688,2109,2.28,75477

In [9]:
#필요없는 열 데이터 제거 
df = seoul_people[['자치구','인구.4','인구.5','인구.3','세대당인구','65세이상고령자']]

           자치구     인구.4     인구.5     인구.3  세대당인구  65세이상고령자
기간
기간         자치구      한국인      한국인      한국인  세대당인구  65세이상고령자
기간         자치구       남자       여자        계  세대당인구  65세이상고령자
2022.1/4    합계  4613910  4892868  9506778   2.14   1628980
2022.1/4   종로구    69911    74364   144275   1.96     28064
2022.1/4    중구    59448    62725   122173   1.92     24742
2022.1/4   용산구   106735   115434   222169      2     39461
2022.1/4   성동구   138847   146226   285073   2.12     46896
2022.1/4   광진구   164346   176361   340707   2.01     52604
2022.1/4  동대문구   166823   171159   337982   1.99     62963
2022.1/4   중랑구   191835   197208   389043   2.07     72851
2022.1/4   성북구   208691   224459   433150    2.2     75719
2022.1/4   강북구   144643   152741   297384   2.05     64961
2022.1/4   도봉구   153716   162382   316098   2.28     65122
2022.1/4   노원구   245663   264823   510486   2.33     89426
2022.1/4   은평구   225640   246619   472259   2.19     88418
2022.1/4  서대문구   145958   159908   305866   2.11     55012
2022.1/4   마포구   173073   195258   368331   2.04     55168
2022.1/4   양천구   218554   227628   446182   2.45     69953
2022.1/4   강서구   275422   297624   573046    2.1     93924
2022.1/4   구로구   195002   201015   396017   2.18     73864
2022.1/4   금천구   116568   114530   231098   1.95     41819
2022.1/4  영등포구   185696   191044   376740      2     63547
2022.1/4   동작구   186648   199369   386017   2.07     67470
2022.1/4   관악구   244409   241966   486375   1.74     80686
2022.1/4   서초구   195806   214017   409823   2.41     61404
2022.1/4   강남구   254866   277711   532577   2.27     79575
2022.1/4   송파구   319407   343200   662607   2.32     99854
2022.1/4   강동구   226203   235097   461300   2.28     75477

In [18]:
#필요없는 행 데이터 제거
df_1 = df[3:]
df_1

           자치구    인구.4    인구.5    인구.3 세대당인구 65세이상고령자
기간
2022.1/4   종로구   69911   74364  144275  1.96    28064
2022.1/4    중구   59448   62725  122173  1.92    24742
2022.1/4   용산구  106735  115434  222169     2    39461
2022.1/4   성동구  138847  146226  285073  2.12    46896
2022.1/4   광진구  164346  176361  340707  2.01    52604
2022.1/4  동대문구  166823  171159  337982  1.99    62963
2022.1/4   중랑구  191835  197208  389043  2.07    72851
2022.1/4   성북구  208691  224459  433150   2.2    75719
2022.1/4   강북구  144643  152741  297384  2.05    64961
2022.1/4   도봉구  153716  162382  316098  2.28    65122
2022.1/4   노원구  245663  264823  510486  2.33    89426
2022.1/4   은평구  225640  246619  472259  2.19    88418
2022.1/4  서대문구  145958  159908  305866  2.11    55012
2022.1/4   마포구  173073  195258  368331  2.04    55168
2022.1/4   양천구  218554  227628  446182  2.45    69953
2022.1/4   강서구  275422  297624  573046   2.1    93924
2022.1/4   구로구  195002  201015  396017  2.18    73864
2022.1/4   금천구  116568  114530  231098  1.95    41819
2022.1/4  영등포구  185696  191044  376740     2    63547
2022.1/4   동작구  186648  199369  386017  2.07    67470
2022.1/4   관악구  244409  241966  486375  1.74    80686
2022.1/4   서초구  195806  214017  409823  2.41    61404
2022.1/4   강남구  254866  277711  532577  2.27    79575
2022.1/4   송파구  319407  343200  662607  2.32    99854
2022.1/4   강동구  226203  235097  461300  2.28    75477

In [20]:
# 인덱스를 날짜에서 자치구로 변경
#df_2 = df_1.set_index(keys='자치구')

In [31]:
df_1.rename(columns={'인구.4':'남자인구수','인구.5':'여자인구수','인구.3':'남자여자인구수합'}, inplace=True)

C:\Users\woosung\AppData\Local\Temp\ipykernel_9388\2360422683.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1.rename(columns={'인구.4':'남자인구수','인구.5':'여자인구수','인구.3':'남자여자인구수합'}, inplace=True)

In [33]:
df_1

           자치구   남자인구수   여자인구수 남자여자인구수합 세대당인구 65세이상고령자
기간
2022.1/4   종로구   69911   74364   144275  1.96    28064
2022.1/4    중구   59448   62725   122173  1.92    24742
2022.1/4   용산구  106735  115434   222169     2    39461
2022.1/4   성동구  138847  146226   285073  2.12    46896
2022.1/4   광진구  164346  176361   340707  2.01    52604
2022.1/4  동대문구  166823  171159   337982  1.99    62963
2022.1/4   중랑구  191835  197208   389043  2.07    72851
2022.1/4   성북구  208691  224459   433150   2.2    75719
2022.1/4   강북구  144643  152741   297384  2.05    64961
2022.1/4   도봉구  153716  162382   316098  2.28    65122
2022.1/4   노원구  245663  264823   510486  2.33    89426
2022.1/4   은평구  225640  246619   472259  2.19    88418
2022.1/4  서대문구  145958  159908   305866  2.11    55012
2022.1/4   마포구  173073  195258   368331  2.04    55168
2022.1/4   양천구  218554  227628   446182  2.45    69953
2022.1/4   강서구  275422  297624   573046   2.1    93924
2022.1/4   구로구  195002  201015   396017  2.18    73864
2022.1/4   금천구  116568  114530   231098  1.95    41819
2022.1/4  영등포구  185696  191044   376740     2    63547
2022.1/4   동작구  186648  199369   386017  2.07    67470
2022.1/4   관악구  244409  241966   486375  1.74    80686
2022.1/4   서초구  195806  214017   409823  2.41    61404
2022.1/4   강남구  254866  277711   532577  2.27    79575
2022.1/4   송파구  319407  343200   662607  2.32    99854
2022.1/4   강동구  226203  235097   461300  2.28    75477

In [ ]:
#타입 변경

In [32]:
# 해당 데이터프레임을 'df_seoul_people.csv' 파일로 저장하세요.
df_1.to_csv("df_seoul_people.csv", index = False)

# 3.데이터 분석하기
+ KeyPoint : 데이터의 형태를 살펴보고 다양한 분석기법을 통해 모델링에 적합하도록 정제요소를 선별할 수 있다.
  * 데이터들의 패턴 탐색
  * 변수들간의 관계 파악

In [ ]:
# 시각화 한글폰트 설정
import seaborn as sns
import matplotlib.pyplot as plt

plt.rc('font', family='nanum')
sns.set(font="NanumGothicCoding",#"NanumGothicCoding", 
        rc={"axes.unicode_minus":False}, # 마이너스 부호 깨짐 현상 해결
        style='darkgrid')

#### [실습문제4] 데이터 분포 알아보기
* 다양한 변수를 기준으로 그래프를 그려보고 인사이트를 도출해보세요.

In [ ]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

In [ ]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

In [ ]:
# 위 차트를 통해 알게된 사실을 정리해봅시다.
# 1. 
# 2.
# 3.

---